<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'DEVM_Theme_Customize_Repeater_Control' => $baseDir . '/core/options/customizer/libs/customize-repeater-control.php',
    'DEVM_Theme_Customize_Repeater_Popup_Control' => $baseDir . '/core/options/customizer/libs/customize-repeater-control-popup.php',
    'DEVM_WP_Customize_Panel' => $baseDir . '/core/options/customizer/libs/sections.php',
    'DEVM_WP_Customize_Section' => $baseDir . '/core/options/customizer/libs/sections.php',
    'Devmonsta\\Bootstrap' => $baseDir . '/core/bootstrap.php',
    'Devmonsta\\Libs\\Customizer' => $baseDir . '/core/libs/customizer.php',
    'Devmonsta\\Libs\\Posts' => $baseDir . '/core/libs/posts.php',
    'Devmonsta\\Libs\\Repeater' => $baseDir . '/core/libs/repeater.php',
    'Devmonsta\\Libs\\Taxonomies' => $baseDir . '/core/libs/taxonomies.php',
    'Devmonsta\\Options\\Customizer\\Controls' => $baseDir . '/core/options/customizer/controls.php',
    'Devmonsta\\Options\\Customizer\\Customizer' => $baseDir . '/core/options/customizer/customizer.php',
    'Devmonsta\\Options\\Customizer\\Structure' => $baseDir . '/core/options/customizer/structure.php',
    'Devmonsta\\Options\\Posts\\Controls' => $baseDir . '/core/options/posts/controls.php',
    'Devmonsta\\Options\\Posts\\Posts' => $baseDir . '/core/options/posts/posts.php',
    'Devmonsta\\Options\\Posts\\Structure' => $baseDir . '/core/options/posts/structure.php',
    'Devmonsta\\Options\\Posts\\Validator' => $baseDir . '/core/options/posts/validator.php',
    'Devmonsta\\Options\\Posts\\View' => $baseDir . '/core/options/posts/view.php',
    'Devmonsta\\Options\\Taxonomies\\Structure' => $baseDir . '/core/options/taxonomies/structure.php',
    'Devmonsta\\Options\\Taxonomies\\Taxonomies' => $baseDir . '/core/options/taxonomies/taxonomies.php',
    'Devmonsta\\Rest' => $baseDir . '/core/rest.php',
    'Devmonsta\\Traits\\Singleton' => $baseDir . '/core/traits/singleton.php',
);
